### PR TITLE
docs(readme): update with list of build depends

### LINKED ISSUE #46: dpkg-checkbuilddeps: error: Unmet build dependencies: pyflakes3 debhelper (>= 7.4.3) while building kernelstub
**Distribution (run `cat /etc/os-release`):** VERSION="20.04 LTS"

**Issue/Bug Description:** I wanted to fix the wake up from hibernation issue and for that I was installing kernelstub found [here](https://github.com/pop-os/pop/issues/349#issuecomment-593423396) and it fails with following issue
image

**Steps to reproduce (if you know):** 
```
debuild -b -us -uc
```

**Expected behavior:** It should create the instalable file.

### PR DESCRIPTION
**Pull request by isantop**
Adds a list of build dependencies which need to be installed to build the package locally. Additionally adds instructions for adding the build-deps on Pop_OS (where the kernelstub source package is available).

Fixes #46

### CODE REVIEW

**Review by bflanagin — COMMENTED** [review]
When following along with the addition and then running. 

`debuild -b -us -us`

I get:
```
Command 'debuild' not found, but can be installed with:
sudo apt install devscripts
```
Should that package be added to the to the readme as well?

**Comment by jacobgkau** [comment]
I've replaced `debuild` with `dpkg-buildpackage` in the example so we don't have to worry about installing `devscripts` (I was going to just add installing `devscripts`, but I wasn't sure whether to list it as a build dependency or put it in its own section.) It looks like the only difference when running with `debuild` will be that it runs `lintian` automatically, which shouldn't affect the .deb output. @isantop can correct me if this was wrong.

I also changed Pop_OS to Pop!_OS, because branding.

**Comment by isantop** [comment]
My thought on `debuild`/`devscripts` is that that's something of a general debian-building package which is helpful for anyone manipulating debian packages (or source packages). However, I can see that it's probably better to replace it with the actual command that `debuild` uses to actually build the binary package.

**Review by bflanagin — APPROVED** [review]
I'm good with it if everyone else is.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
