### PR TITLE
Upstream 3.2

### PR DESCRIPTION
**Pull request by isantop**
The PR releases Kernelstub  3.2 into the stable branch. This new version includes a number of fixes and new features:

* Systemd-boot entry files are now named (nearly) uniquely for each OS, ensuring that parallel installs of the same OS don't conflict with loader entry files. 
* Adds new online documentation (manpage)

Requires #34

### CODE REVIEW

**Comment by mmstick** [comment]
What naming conventions can be expect the entries and their titles. Asking because the upgrade daemon / distinst interacts with the systemd entry configurations to determine which entry to use as the recovery or OS option.

**Comment by isantop** [comment]
@mmstick Entry files are now named `{os-name}-{hostname}({uuid-first-segment})-(current|oldkern).conf`

For example:
```
'Pop_OS-akira(6ebccc2b)-current.conf' 
```
Where the OS Name is `Pop_OS`, the hostname is `akira`, and the first segment of the UUID is `6ebccc2b`.

**Comment by isantop** [comment]
They also get Title fields with the OS name and the hostname as well, although those shouldn't affect the filename at all, only how the entries are displayed in the menu.

**Comment by mmstick** [comment]
How's the recovery partition named?

**Comment by isantop** [comment]
This PR (or any of Kernelstub, in fact) does not add or modify the recovery partition entry. That's still set by (I believe) the installer, which names it `Recovery-{FATID}.conf`

Mine is `Recovery-F44D-2139.conf`

**Comment by jackpot51** [comment]
And if the hostname is changed, what happens?

**Comment by jackpot51** [comment]
I think in order for this to be merged, first I would like to merge all the documentation changes and bug/syntax fixes. Then this PR containing behaviour changes will need more in-depth testing.

**Pull request closed without merging**
