### PR TITLE
Unify branches

### PR DESCRIPTION
**Pull request by isantop**
This PR will unify our separate master branches into a single master for easier management in the future, especially with immutable bases.

### CODE REVIEW

**Comment by isantop** [comment]
Requesting an explicit review from @13r0ck to ensure that all required commits from `_jammy` are brought into the older versions as well.

**Review by 13r0ck — CHANGES_REQUESTED** [review]
4c42f3265b626433931453b64f61e16d69b8ed12 should be dropped

**Comment by isantop** [comment]
@13r0ck I've reverted that commit as of 25b753c

**Review by 13r0ck — APPROVED** [review]

**Comment by mmstick** [comment]
Package is failing to build for that last commit

**Comment by isantop** [comment]
Note to QA: This will be merged on all versions, so it will need more testing than is indicated by the build server. For the purposes of testing, I've created a branch of this `master-jammy` which should build for all versions and can be added/tested on all versions.

**Comment by isantop** [comment]
The build is failing due to an error on the build server, namely: 

`12:53:45 E: apt-get update failed`

**Comment by jacobgkau** [comment]
> The build is failing due to an error on the build server, namely:
> 
> `12:53:45 E: apt-get update failed`

Attempting to build locally on Jammy still gives a different error:

```
make[1]: Entering directory '/home/jacob/Work/kernelstub'
py3versions: no X-Python3-Version in control file, using supported versions
set -ex; for python in python3.10; do \
    $python -Werror setup.py test; \
done
+ python3.10 -Werror setup.py test
Traceback (most recent call last):
  File "/home/jacob/Work/kernelstub/setup.py", line 22, in <module>
    from distutils.core import setup
  File "/usr/lib/python3.10/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 13, in <module>
    import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
  File "/usr/lib/python3.10/imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib and slated "
DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses

Original exception was:
Traceback (most recent call last):
  File "/home/jacob/Work/kernelstub/setup.py", line 22, in <module>
    from distutils.core import setup
  File "/usr/lib/python3.10/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
make[1]: *** [debian/rules:17: override_dh_auto_test] Error 1
make[1]: Leaving directory '/home/jacob/Work/kernelstub'
make: *** [debian/rules:7: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by jacobgkau** [comment]
I rebased this branch on `master` so it includes what was merged from https://github.com/pop-os/kernelstub/pull/64. This got the build working on my local system.

**Comment by isantop** [comment]
I updated the build branch for the other versions as well

**Comment by gangwerz** [comment]
The new kernelstub build works on a fresh Jammy install

- [X] Can print the current boot config
- [X] Can set the boot config with:
```bash
sudo kernelstub -k /boot/vmlinuz-5.18.10-76051810-generic -i /boot/initrd.img-5.18.10-76051810-generic -o "loglevel=0 systemd.show_status=false splash"
```
- [X] Can add a boot paramater:
```bash
sudo kernelstub -a quiet
```

**Comment by n3m0-22** [comment]
All tests on Focal are passing. The tests mentioned above pass. I also updated the kernel with no issue with switching between kernels at boot, and no issue with using kernelstub to change the default kernel.

**Review by gangwerz — APPROVED** [review]
Changes look good!

**Pull request merged**
