### PR TITLE
 Make kernel options more robust

### PR DESCRIPTION
**Pull request by brs17**
Duplicate of https://github.com/pop-os/kernelstub/pull/26 but CI will build this pr.

### CODE REVIEW

**Comment by isantop** [comment]
@brs17 If you git pull this branch from the upstream, the build issues will be fixed.

**Comment by brs17** [comment]
I tested the patch and this is what I got after running updates. I also ran `sudo kernelstub -v` that output is provided as well. Looks like we got ourselves a little traceback!

screenshot from 2018-09-12 08-15-14

Contents of `/etc/kernelstub/configruation`:
```
{
  "default": {
    "kernel_options": [
      "quiet",
      "loglevel=0",
      "vga=current",
      "systemd.show_status=false"
    ],
    "esp_path": "/boot/efi",
    "setup_loader": true,
    "manage_mode": true,
    "force_update": false,
    "live_mode": true,
    "config_rev": 3
  },
  "user": {
    "kernel_options": "loglevel=0 nvidia.NVreg_EnableBacklightHandler=1 quiet splash systemd.show_status=false",
    "esp_path": "/boot/efi",
    "setup_loader": true,
    "manage_mode": true,
    "force_update": false,
    "live_mode": false,
    "config_rev": 3
  }
}
```

**Comment by isantop** [comment]
@brs17 Can you get a run with -vv? I'm missing some of the output to know what went wrong and where the error is.

**Comment by brs17** [comment]
I haven't been able to reproduce that since that happened once this morning :'( not it seems to work just fine.

**Comment by jackpot51** [comment]
It is highly unlikely that the change in this PR caused that error to occur, so I would say this should be merged

**Pull request merged**
